[app]
project_name = "vite-react-basic"
name = "Vite React Basic"
identifier = "dev.cefari.vite-react-basic"

[frontend]
dist = "frontend/dist"
build_command = ["deno", "task", "build:frontend"]
dev_command = ["deno", "task", "dev:frontend", "--host", "127.0.0.1", "--port", "{port}"]
dev_port = 5111

[daemon]
entry = "daemon/main.ts"

[package]
product_name = "Vite React Basic"
version = "0.1.0"
