[package]
name = "cefari-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "cefari"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap = { workspace = true, features = ["derive"] }
cefari-core = { path = "../cefari-core" }
download-cef.workspace = true
duct.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
xshell.workspace = true

[dev-dependencies]
cargo-packager-updater.workspace = true

[lints]
workspace = true
