// This file has been generated by Specta. Do not edit this file manually.
export type ActiveNotification = {
	id: string,
	userInfo: { [key in string]: string },
};

export type AppDataDirInfo = {
	rootKind: string,
	displayPath: string,
};

export type CefariIpcCommand = { command: "appQuit" } | { command: "windowCurrent" } | { command: "windowList" } | { command: "windowCreate"; payload: WindowCreateRequest } | { command: "windowShow"; payload: WindowTargetRequest } | { command: "windowFocus"; payload: WindowTargetRequest } | { command: "windowClose"; payload: WindowTargetRequest } | { command: "windowSetTitle"; payload: WindowSetTitleRequest } | { command: "openLogs" } | { command: "reloadUi" } | { command: "openExternalUrl"; payload: OpenExternalUrlRequest } | { command: "updateState" } | { command: "updateCheck" } | { command: "updateApply"; payload: UpdateApplyRequest } | { command: "updateRestart" } | { command: "serviceStatus" } | { command: "trayRestoreWindow" } | { command: "download"; payload: DownloadCommand } | { command: "notification"; payload: NotificationCommand } | { command: "dialog"; payload: DialogCommand } | { command: "files"; payload: FilesCommand };

export type CefariIpcError = { code: "invalidCommand"; details: {
	message: string,
} } | { code: "denied"; details: {
	message: string,
} } | { code: "unknownCommand"; details: {
	command: string,
} } | { code: "unsupported"; details: {
	command: string,
	reason: string,
} };

export type CefariIpcEvent = { event: "windowCreated"; payload: WindowStateEvent } | { event: "windowShown"; payload: WindowStateEvent } | { event: "windowFocused"; payload: WindowStateEvent } | { event: "windowBlurred"; payload: WindowStateEvent } | { event: "windowCloseRequested"; payload: WindowStateEvent } | { event: "windowClosed"; payload: WindowIdEvent } | { event: "windowMoved"; payload: WindowStateEvent } | { event: "windowResized"; payload: WindowStateEvent } | { event: "windowTitleChanged"; payload: WindowStateEvent } | { event: "deepLinkOpened"; payload: DeepLinkOpenEvent } | { event: "trayRestoreWindow" } | { event: "updateStateChanged"; payload: UpdateStateResult } | { event: "serviceStatusChanged"; payload: ServiceStatusResult } | { event: "download"; payload: DownloadEvent } | { event: "notification"; payload: NotificationEvent };

export type CefariIpcOutcome = { status: "ok"; payload: CefariIpcResult } | { status: "err"; payload: CefariIpcError };

export type CefariIpcRequest = {
	id: string,
	command: CefariIpcCommand,
};

export type CefariIpcResponse = {
	id: string,
	outcome: CefariIpcOutcome,
};

export type CefariIpcResult = { result: "empty" } | { result: "window"; payload: WindowState } | { result: "windowList"; payload: WindowListResult } | { result: "reloadUi" } | { result: "externalUrl"; payload: ExternalUrlResult } | { result: "updateState"; payload: UpdateStateResult } | { result: "updateCheck"; payload: UpdateCheckResult } | { result: "updateApply"; payload: UpdateApplyResult } | { result: "serviceStatus"; payload: ServiceStatusResult } | { result: "tray"; payload: TrayResult } | { result: "download"; payload: DownloadResult } | { result: "notification"; payload: NotificationResult } | { result: "dialog"; payload: DialogResult } | { result: "file"; payload: FileResult };

export type CopyFileRequest = {
	from: string,
	to: string,
};

export type DeepLinkOpenEvent = {
	url: string,
};

export type DialogCommand = { dialog: "openFile"; payload: DialogRequest } | { dialog: "openFiles"; payload: DialogRequest } | { dialog: "chooseFolder"; payload: DialogRequest } | { dialog: "chooseFolders"; payload: DialogRequest } | { dialog: "saveFile"; payload: DialogRequest };

export type DialogDefaultDirectory = { kind: "appData"; path: string | null } | { kind: "native"; path: string };

export type DialogFilter = {
	name: string,
	extensions: string[],
};

export type DialogModality = "window" | "app";

export type DialogRequest = {
	title: string | null,
	filters: DialogFilter[],
	defaultDirectory: DialogDefaultDirectory | null,
	defaultName: string | null,
	modality: DialogModality | null,
	canCreateDirectories: boolean | null,
};

export type DialogResult = { result: "canceled" } | { result: "selected"; payload: {
	paths: DialogSelectedPath[],
} };

export type DialogSelectedPath = {
	path: string,
	name: string,
	kind: FileKind,
};

export type DirEntry = {
	name: string,
	path: string,
	kind: FileKind,
};

export type DownloadCanceledEvent = {
	id: string,
	reason: string,
};

export type DownloadCommand = { download: "cancel"; payload: DownloadIdRequest } | { download: "reveal"; payload: DownloadIdRequest };

export type DownloadCompletedEvent = {
	id: string,
	url: string,
	destinationPath: string,
	receivedBytes: number | null,
	totalBytes: number | null,
};

export type DownloadEvent = { event: "started"; payload: DownloadStartedEvent } | { event: "progress"; payload: DownloadProgressEvent } | { event: "completed"; payload: DownloadCompletedEvent } | { event: "canceled"; payload: DownloadCanceledEvent } | { event: "failed"; payload: DownloadFailedEvent };

export type DownloadFailedEvent = {
	id: string,
	reason: string,
};

export type DownloadIdRequest = {
	id: string,
};

export type DownloadIdResult = {
	id: string,
};

export type DownloadProgressEvent = {
	id: string,
	receivedBytes: number | null,
	totalBytes: number | null,
	percentComplete: number | null,
};

export type DownloadResult = { result: "canceled"; payload: DownloadIdResult } | { result: "revealed"; payload: DownloadIdResult };

export type DownloadStartedEvent = {
	id: string,
	url: string,
	suggestedName: string,
	destinationPath: string | null,
	totalBytes: number | null,
};

export type ExternalUrlResult = {
	url: string,
};

export type FileContents = { kind: "text"; value: string } | { kind: "base64"; value: string };

export type FileEncoding = "utf8" | "base64";

export type FileKind = "file" | "directory" | "symlink" | "other";

export type FilePathRequest = {
	path: string,
};

export type FileReadRequest = {
	path: string,
	encoding: FileEncoding | null,
};

export type FileResult = { result: "appDataDir"; payload: AppDataDirInfo } | { result: "text"; payload: {
	contents: string,
} } | { result: "base64"; payload: {
	contents: string,
} } | { result: "dirEntries"; payload: {
	entries: DirEntry[],
} } | { result: "stat"; payload: FileStat } | { result: "access"; payload: {
	ok: boolean,
} } | { result: "written"; payload: FileWriteResult } | { result: "empty" };

export type FileStat = {
	path: string,
	kind: FileKind,
	size: number | null,
	modifiedAtMs: number | null,
	createdAtMs: number | null,
};

export type FileWriteOptions = {
	createParents: boolean,
	overwrite: boolean,
};

export type FileWriteRequest = {
	path: string,
	contents: FileContents,
	options: FileWriteOptions,
};

export type FileWriteResult = {
	path: string,
	bytesWritten: number | null,
};

export type FilesCommand = { file: "appDataDir" } | { file: "readFile"; payload: FileReadRequest } | { file: "writeFile"; payload: FileWriteRequest } | { file: "readdir"; payload: ReadDirRequest } | { file: "mkdir"; payload: MkdirRequest } | { file: "rm"; payload: RmRequest } | { file: "rename"; payload: RenameRequest } | { file: "copyFile"; payload: CopyFileRequest } | { file: "stat"; payload: FilePathRequest } | { file: "access"; payload: FilePathRequest };

export type MkdirRequest = {
	path: string,
	recursive: boolean,
};

export type NotificationAction = "default" | "dismiss" | { other: string };

export type NotificationCapabilities = {
	permissionState: boolean,
	permissionPrompt: boolean,
	subtitle: boolean,
	image: boolean,
	icon: boolean,
	iconRoundCrop: boolean,
	threadId: boolean,
	categories: boolean,
	actionButtons: boolean,
	textInputActions: boolean,
	userInfo: boolean,
	xdgCategory: boolean,
	activeNotifications: boolean,
	removeDelivered: boolean,
	responseEvents: boolean,
	coldStartActivation: boolean,
};

export type NotificationCategory = {
	id: string,
	actions: NotificationCategoryAction[],
};

export type NotificationCategoryAction = { type: "action"; id: string; title: string } | { type: "textInput"; id: string; title: string; inputButtonTitle: string; inputPlaceholder: string };

export type NotificationCommand = { notification: "permissionState" } | { notification: "requestPermission" } | { notification: "capabilities" } | { notification: "registerCategories"; payload: NotificationRegisterCategoriesRequest } | { notification: "send"; payload: NotificationSendRequest } | { notification: "active" } | { notification: "removeDelivered"; payload: NotificationRemoveDeliveredRequest } | { notification: "removeAllDelivered" };

export type NotificationEvent = { event: "response"; payload: NotificationResponseEvent };

export type NotificationMediaReference = { source: "appResource"; path: string } | { source: "appData"; path: string };

export type NotificationRegisterCategoriesRequest = {
	categories: NotificationCategory[],
};

export type NotificationRemoveDeliveredRequest = {
	ids: string[],
};

export type NotificationResponseEvent = {
	id: string,
	action: NotificationAction,
	userText: string | null,
	userInfo: { [key in string]: string },
};

export type NotificationResult = { result: "permissionState"; payload: {
	allowed: boolean,
} } | { result: "permissionRequested"; payload: {
	allowed: boolean,
} } | { result: "capabilities"; payload: NotificationCapabilities } | { result: "categoriesRegistered"; payload: {
	count: number,
} } | { result: "sent"; payload: {
	id: string,
} } | { result: "active"; payload: {
	notifications: ActiveNotification[],
} } | { result: "removed"; payload: {
	count: number,
} } | { result: "permissionDenied" } | { result: "unsupported"; payload: {
	reason: string,
} };

export type NotificationSendRequest = {
	title: string,
	body: string | null,
	subtitle: string | null,
	image: NotificationMediaReference | null,
	icon: NotificationMediaReference | null,
	iconRoundCrop: boolean,
	threadId: string | null,
	categoryId: string | null,
	userInfo: { [key in string]: string },
	xdgCategory: NotificationXdgCategory | null,
};

export type NotificationXdgCategory = "call" | "callEnded" | "callIncoming" | "callUnanswered" | "device" | "deviceAdded" | "deviceError" | "deviceRemoved" | "email" | "emailArrived" | "emailBounced" | "im" | "imError" | "imReceived" | "network" | "networkConnected" | "networkDisconnected" | "networkError" | "presence" | "presenceOffline" | "presenceOnline" | "transfer" | "transferComplete" | "transferError";

export type OpenExternalUrlRequest = {
	url: string,
};

export type ReadDirRequest = {
	path: string,
	withFileTypes: boolean,
};

export type RenameRequest = {
	from: string,
	to: string,
};

export type RmRequest = {
	path: string,
	recursive: boolean,
	force: boolean,
};

export type ServiceStatusResult = {
	status: string,
};

export type TrayResult = {
	restored: boolean,
};

export type UpdateApplyRequest = {
	updateId: string | null,
};

export type UpdateApplyResult = {
	state: UpdateStateKind,
	version: string | null,
	restartRequired: boolean,
};

export type UpdateCheckResult = {
	state: UpdateStateKind,
	version: string | null,
	updateId: string | null,
};

export type UpdateStateKind = "notConfigured" | "current" | "checking" | "available" | "applying" | "readyToRestart" | "error";

export type UpdateStateResult = {
	state: UpdateStateKind,
};

export type WindowCreateRequest = {
	id: string | null,
	route: string | null,
	title: string | null,
	width: number | null,
	height: number | null,
	minWidth: number | null,
	minHeight: number | null,
	maxWidth: number | null,
	maxHeight: number | null,
	x: number | null,
	y: number | null,
	visible: boolean | null,
	focused: boolean | null,
	resizable: boolean | null,
	decorations: boolean | null,
	alwaysOnTop: boolean | null,
	parentId: string | null,
	modal: boolean | null,
	persistKey: string | null,
};

export type WindowIdEvent = {
	windowId: string,
};

export type WindowKind = "main" | "secondary";

export type WindowListResult = {
	windows: WindowState[],
};

export type WindowSetTitleRequest = {
	target: WindowTarget | null,
	title: string,
};

export type WindowState = {
	id: string,
	kind: WindowKind,
	visible: boolean,
	focused: boolean,
	title: string,
	modal: boolean,
	parentId: string | null,
	route: string | null,
};

export type WindowStateEvent = {
	windowId: string,
	state: WindowState,
};

export type WindowTarget = {
	id: string | null,
};

export type WindowTargetRequest = {
	target: WindowTarget | null,
};
