// This file has been generated by Specta. Do not edit this file manually.
export type ActiveNotification = {
	id: string,
	userInfo: { [key in string]: string },
};

export type AppDataDirInfo = {
	rootKind: string,
	displayPath: string,
};

export type CefariIpcCommand = { command: "appQuit" } | { command: "windowShow" } | { command: "windowFocus" } | { command: "windowClose" } | { command: "windowSetTitle"; payload: WindowSetTitleRequest } | { command: "openLogs" } | { command: "reloadUi" } | { command: "openExternalUrl"; payload: OpenExternalUrlRequest } | { command: "updateState" } | { command: "updateCheck" } | { command: "updateApply"; payload: UpdateApplyRequest } | { command: "updateRestart" } | { command: "serviceStatus" } | { command: "trayRestoreWindow" } | { command: "notification"; payload: NotificationCommand } | { command: "files"; payload: FilesCommand };

export type CefariIpcError = { code: "invalidCommand"; details: {
	message: string,
} } | { code: "denied"; details: {
	message: string,
} } | { code: "unknownCommand"; details: {
	command: string,
} } | { code: "unsupported"; details: {
	command: string,
	reason: string,
} };

export type CefariIpcEvent = { event: "windowShown"; payload: WindowState } | { event: "windowFocused"; payload: WindowState } | { event: "windowClosed" } | { event: "trayRestoreWindow" } | { event: "updateStateChanged"; payload: UpdateStateResult } | { event: "serviceStatusChanged"; payload: ServiceStatusResult } | { event: "notification"; payload: NotificationEvent };

export type CefariIpcOutcome = { status: "ok"; payload: CefariIpcResult } | { status: "err"; payload: CefariIpcError };

export type CefariIpcRequest = {
	id: string,
	command: CefariIpcCommand,
};

export type CefariIpcResponse = {
	id: string,
	outcome: CefariIpcOutcome,
};

export type CefariIpcResult = { result: "empty" } | { result: "window"; payload: WindowState } | { result: "reloadUi" } | { result: "externalUrl"; payload: ExternalUrlResult } | { result: "updateState"; payload: UpdateStateResult } | { result: "updateCheck"; payload: UpdateCheckResult } | { result: "updateApply"; payload: UpdateApplyResult } | { result: "serviceStatus"; payload: ServiceStatusResult } | { result: "tray"; payload: TrayResult } | { result: "notification"; payload: NotificationResult } | { result: "file"; payload: FileResult };

export type CopyFileRequest = {
	from: string,
	to: string,
};

export type DirEntry = {
	name: string,
	path: string,
	kind: FileKind,
};

export type ExternalUrlResult = {
	url: string,
};

export type FileContents = { kind: "text"; value: string } | { kind: "base64"; value: string };

export type FileEncoding = "utf8" | "base64";

export type FileKind = "file" | "directory" | "symlink" | "other";

export type FilePathRequest = {
	path: string,
};

export type FileReadRequest = {
	path: string,
	encoding: FileEncoding | null,
};

export type FileResult = { result: "appDataDir"; payload: AppDataDirInfo } | { result: "text"; payload: {
	contents: string,
} } | { result: "base64"; payload: {
	contents: string,
} } | { result: "dirEntries"; payload: {
	entries: DirEntry[],
} } | { result: "stat"; payload: FileStat } | { result: "access"; payload: {
	ok: boolean,
} } | { result: "written"; payload: FileWriteResult } | { result: "empty" };

export type FileStat = {
	path: string,
	kind: FileKind,
	size: number | null,
	modifiedAtMs: number | null,
	createdAtMs: number | null,
};

export type FileWriteOptions = {
	createParents: boolean,
	overwrite: boolean,
};

export type FileWriteRequest = {
	path: string,
	contents: FileContents,
	options: FileWriteOptions,
};

export type FileWriteResult = {
	path: string,
	bytesWritten: number | null,
};

export type FilesCommand = { file: "appDataDir" } | { file: "readFile"; payload: FileReadRequest } | { file: "writeFile"; payload: FileWriteRequest } | { file: "readdir"; payload: ReadDirRequest } | { file: "mkdir"; payload: MkdirRequest } | { file: "rm"; payload: RmRequest } | { file: "rename"; payload: RenameRequest } | { file: "copyFile"; payload: CopyFileRequest } | { file: "stat"; payload: FilePathRequest } | { file: "access"; payload: FilePathRequest };

export type MkdirRequest = {
	path: string,
	recursive: boolean,
};

export type NotificationAction = "default" | "dismiss" | { other: string };

export type NotificationCapabilities = {
	permissionState: boolean,
	permissionPrompt: boolean,
	subtitle: boolean,
	image: boolean,
	icon: boolean,
	iconRoundCrop: boolean,
	threadId: boolean,
	categories: boolean,
	actionButtons: boolean,
	textInputActions: boolean,
	userInfo: boolean,
	xdgCategory: boolean,
	activeNotifications: boolean,
	removeDelivered: boolean,
	responseEvents: boolean,
	coldStartActivation: boolean,
};

export type NotificationCategory = {
	id: string,
	actions: NotificationCategoryAction[],
};

export type NotificationCategoryAction = { type: "action"; id: string; title: string } | { type: "textInput"; id: string; title: string; inputButtonTitle: string; inputPlaceholder: string };

export type NotificationCommand = { notification: "permissionState" } | { notification: "requestPermission" } | { notification: "capabilities" } | { notification: "registerCategories"; payload: NotificationRegisterCategoriesRequest } | { notification: "send"; payload: NotificationSendRequest } | { notification: "active" } | { notification: "removeDelivered"; payload: NotificationRemoveDeliveredRequest } | { notification: "removeAllDelivered" };

export type NotificationEvent = { event: "response"; payload: NotificationResponseEvent };

export type NotificationMediaReference = { source: "appResource"; path: string } | { source: "appData"; path: string };

export type NotificationRegisterCategoriesRequest = {
	categories: NotificationCategory[],
};

export type NotificationRemoveDeliveredRequest = {
	ids: string[],
};

export type NotificationResponseEvent = {
	id: string,
	action: NotificationAction,
	userText: string | null,
	userInfo: { [key in string]: string },
};

export type NotificationResult = { result: "permissionState"; payload: {
	allowed: boolean,
} } | { result: "permissionRequested"; payload: {
	allowed: boolean,
} } | { result: "capabilities"; payload: NotificationCapabilities } | { result: "categoriesRegistered"; payload: {
	count: number,
} } | { result: "sent"; payload: {
	id: string,
} } | { result: "active"; payload: {
	notifications: ActiveNotification[],
} } | { result: "removed"; payload: {
	count: number,
} } | { result: "permissionDenied" } | { result: "unsupported"; payload: {
	reason: string,
} };

export type NotificationSendRequest = {
	title: string,
	body: string | null,
	subtitle: string | null,
	image: NotificationMediaReference | null,
	icon: NotificationMediaReference | null,
	iconRoundCrop: boolean,
	threadId: string | null,
	categoryId: string | null,
	userInfo: { [key in string]: string },
	xdgCategory: NotificationXdgCategory | null,
};

export type NotificationXdgCategory = "device" | "deviceAdded" | "deviceError" | "deviceRemoved" | "email" | "emailArrived" | "emailBounced" | "im" | "imError" | "imReceived" | "network" | "networkConnected" | "networkDisconnected" | "networkError" | "presence" | "presenceOffline" | "presenceOnline" | "transfer" | "transferComplete" | "transferError";

export type OpenExternalUrlRequest = {
	url: string,
};

export type ReadDirRequest = {
	path: string,
	withFileTypes: boolean,
};

export type RenameRequest = {
	from: string,
	to: string,
};

export type RmRequest = {
	path: string,
	recursive: boolean,
	force: boolean,
};

export type ServiceStatusResult = {
	status: string,
};

export type TrayResult = {
	restored: boolean,
};

export type UpdateApplyRequest = {
	updateId: string | null,
};

export type UpdateApplyResult = {
	state: UpdateStateKind,
	version: string | null,
	restartRequired: boolean,
};

export type UpdateCheckResult = {
	state: UpdateStateKind,
	version: string | null,
	updateId: string | null,
};

export type UpdateStateKind = "notConfigured" | "current" | "checking" | "available" | "applying" | "readyToRestart" | "error";

export type UpdateStateResult = {
	state: UpdateStateKind,
};

export type WindowSetTitleRequest = {
	title: string,
};

export type WindowState = {
	visible: boolean,
	focused: boolean,
	title: string,
};
