// @generated by crates/cefari-core/build.rs; do not edit by hand.
export type CefariTarget = "desktop" | "ios" | "android";

export type PlatformSupport =
  | "portable"
  | "hostSpecific"
  | "desktopOnly"
  | "mobileOnly"
  | "deferred";

export type IpcCapabilitySupport = {
  name: string;
  support: PlatformSupport;
  targets: readonly CefariTarget[];
  rationale: string;
};

export const ipcCapabilitySupport = [
  {
    name: "app",
    support: "hostSpecific",
    targets: ["desktop", "ios", "android"],
    rationale: "App metadata can be shared, but lifecycle behavior differs by host.",
  },
  {
    name: "windows",
    support: "desktopOnly",
    targets: ["desktop"],
    rationale: "Desktop windows should not be treated as mobile screens or routes.",
  },
  {
    name: "shell",
    support: "hostSpecific",
    targets: ["desktop", "ios", "android"],
    rationale: "External URL and shell-style actions map to different host mechanisms.",
  },
  {
    name: "updates",
    support: "desktopOnly",
    targets: ["desktop"],
    rationale: "The desktop updater contract should not be reused for app-store mobile updates.",
  },
  {
    name: "service",
    support: "desktopOnly",
    targets: ["desktop"],
    rationale: "Local daemon service management is a desktop runtime capability.",
  },
  {
    name: "tray",
    support: "desktopOnly",
    targets: ["desktop"],
    rationale: "Tray integration is a desktop OS concept with no mobile equivalent.",
  },
  {
    name: "downloads",
    support: "hostSpecific",
    targets: ["desktop", "ios", "android"],
    rationale: "Downloads exist across hosts, but destination visibility and storage policy differ.",
  },
  {
    name: "logs",
    support: "hostSpecific",
    targets: ["desktop", "ios", "android"],
    rationale: "Log capture is shared at the API level, but persistence and export routing differ by host.",
  },
  {
    name: "notifications",
    support: "hostSpecific",
    targets: ["desktop", "ios", "android"],
    rationale: "Notification intent is shared, but permissions and delivery behavior differ by host.",
  },
  {
    name: "dialogs",
    support: "hostSpecific",
    targets: ["desktop", "ios", "android"],
    rationale: "Native dialog intent is shared, but presentation and modality differ by host.",
  },
  {
    name: "files",
    support: "hostSpecific",
    targets: ["desktop", "ios", "android"],
    rationale: "File access is shared at the API level but sandboxed and permission-mediated by host.",
  },
  {
    name: "workers",
    support: "hostSpecific",
    targets: ["desktop", "ios", "android"],
    rationale: "Worker-like execution may exist across hosts, but lifecycle limits differ.",
  },
] as const satisfies readonly IpcCapabilitySupport[];

export function capabilitySupport(name: string): IpcCapabilitySupport | undefined {
  return ipcCapabilitySupport.find((capability) => capability.name === name);
}

export function supportsTarget(name: string, target: CefariTarget): boolean {
  return capabilitySupport(name)?.targets.includes(target) ?? false;
}
