use std::{
    fs,
    path::{Path, PathBuf},
    process::Command as ProcessCommand,
};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};

mod project;

use project::ProjectConfig;

#[derive(Debug, Parser)]
#[command(name = "cefari")]
#[command(about = "Create, develop, build, package, sign, and release Cefari apps.")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Create a new Cefari project.
    Init {
        /// Directory to create. Defaults to ./cefari-app.
        #[arg(default_value = "cefari-app")]
        path: PathBuf,

        /// Application display name.
        #[arg(long)]
        name: Option<String>,
    },
    /// Run the local development environment.
    Dev,
    /// Build frontend, daemon, and desktop artifacts.
    Build,
    /// Package a built Cefari app.
    Package,
    /// Code sign a packaged app.
    Codesign,
    /// Notarize a signed app.
    Notarize,
    /// Generate update artifacts.
    MakeUpdate,
    /// Check local tool and project health.
    Doctor,
    /// Print environment and project information.
    Info,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Init { path, name } => init_project(&path, name.as_deref()),
        Command::Dev => todo_command("dev"),
        Command::Build => todo_command("build"),
        Command::Package => todo_command("package"),
        Command::Codesign => todo_command("codesign"),
        Command::Notarize => todo_command("notarize"),
        Command::MakeUpdate => todo_command("make-update"),
        Command::Doctor => {
            doctor();
            Ok(())
        }
        Command::Info => {
            info();
            Ok(())
        }
    }
}

fn todo_command(name: &str) -> Result<()> {
    anyhow::bail!("cefari {name} is not implemented yet")
}

fn init_project(path: &Path, name: Option<&str>) -> Result<()> {
    if path.exists() {
        anyhow::bail!("refusing to initialize existing path: {}", path.display());
    }

    let display_name = name.map_or_else(|| default_display_name(path), str::to_owned);
    let identifier = format!("dev.cefari.{}", identifier_slug(&display_name));

    fs::create_dir_all(path.join("frontend"))
        .with_context(|| format!("failed to create frontend directory at {}", path.display()))?;
    fs::create_dir_all(path.join("daemon"))
        .with_context(|| format!("failed to create daemon directory at {}", path.display()))?;

    write_file(
        &path.join("cefari.toml"),
        &format!(
            r#"[app]
name = "{display_name}"
identifier = "{identifier}"

[frontend]
dist = "frontend/dist"

[daemon]
entry = "daemon/main.ts"

[package]
product_name = "{display_name}"
"#
        ),
    )?;
    write_file(&path.join("frontend/index.html"), FRONTEND_TEMPLATE)?;
    write_file(&path.join("daemon/main.ts"), DAEMON_TEMPLATE)?;
    write_file(
        &path.join("README.md"),
        &format!(
            r"# {display_name}

Generated by `cefari init`.

```bash
cefari dev
cefari build
cefari package
```
"
        ),
    )?;

    println!("created Cefari project at {}", path.display());
    Ok(())
}

fn doctor() {
    println!("Cefari doctor");
    print_tool_status("cargo");
    print_tool_status("deno");
    print_tool_status("cargo-packager");
    print_tool_status("cargo-codesign");
}

fn info() {
    println!("cefari-cli {}", env!("CARGO_PKG_VERSION"));
    println!("target os: {}", std::env::consts::OS);
    println!("target arch: {}", std::env::consts::ARCH);

    match ProjectConfig::load_from_dir(".") {
        Ok(project) => {
            println!("project: {}", project.app.name);
            println!("identifier: {}", project.app.identifier);
        }
        Err(project::LoadProjectError::Missing { .. }) => {
            println!("project: not found");
        }
        Err(error) => {
            println!("project: invalid ({error})");
        }
    }
}

fn print_tool_status(tool: &str) {
    if tool_available(tool) {
        println!("{tool}: found");
    } else {
        println!("{tool}: missing");
    }
}

fn tool_available(tool: &str) -> bool {
    ProcessCommand::new(tool)
        .arg("--version")
        .output()
        .is_ok_and(|output| output.status.success())
}

fn write_file(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("failed to write {}", path.display()))
}

fn default_display_name(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or("cefari-app")
        .to_owned()
}

fn identifier_slug(value: &str) -> String {
    let mut slug = String::new();
    let mut last_was_dash = false;

    for character in value.chars().flat_map(char::to_lowercase) {
        if character.is_ascii_alphanumeric() {
            slug.push(character);
            last_was_dash = false;
        } else if !last_was_dash && !slug.is_empty() {
            slug.push('-');
            last_was_dash = true;
        }
    }

    slug.trim_matches('-').to_owned()
}

const FRONTEND_TEMPLATE: &str = r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cefari App</title>
  </head>
  <body>
    <main id="app"></main>
  </body>
</html>
"#;

const DAEMON_TEMPLATE: &str = r#"console.log("cefari daemon starting");
"#;

#[cfg(test)]
mod tests {
    use std::{
        fs,
        time::{SystemTime, UNIX_EPOCH},
    };

    use clap::Parser;

    use super::{Cli, Command, ProjectConfig, identifier_slug, init_project};

    #[test]
    fn parses_planned_commands() {
        assert!(matches!(
            Cli::try_parse_from(["cefari", "init", "sample"])
                .expect("init should parse")
                .command,
            Command::Init { .. }
        ));
        assert!(matches!(
            Cli::try_parse_from(["cefari", "doctor"])
                .expect("doctor should parse")
                .command,
            Command::Doctor
        ));
        assert!(matches!(
            Cli::try_parse_from(["cefari", "make-update"])
                .expect("make-update should parse")
                .command,
            Command::MakeUpdate
        ));
    }

    #[test]
    fn creates_project_scaffold() {
        let root = temp_project_path();
        init_project(&root, Some("Example App")).expect("project should initialize");

        let manifest = fs::read_to_string(root.join("cefari.toml")).expect("manifest should exist");
        assert!(manifest.contains(r#"name = "Example App""#));
        assert!(manifest.contains(r#"identifier = "dev.cefari.example-app""#));
        assert!(root.join("frontend/index.html").exists());
        assert!(root.join("daemon/main.ts").exists());
        assert!(root.join("README.md").exists());

        let project = ProjectConfig::load_from_dir(&root).expect("generated manifest should parse");
        assert_eq!(project.app.name, "Example App");
        assert_eq!(project.frontend.dist, "frontend/dist");
        assert_eq!(project.daemon.entry, "daemon/main.ts");

        fs::remove_dir_all(root).expect("temp project should be removable");
    }

    #[test]
    fn refuses_existing_project_path() {
        let root = temp_project_path();
        fs::create_dir_all(&root).expect("temp dir should be created");

        let error = init_project(&root, Some("Existing")).expect_err("existing path should fail");
        assert!(error.to_string().contains("refusing to initialize"));

        fs::remove_dir_all(root).expect("temp project should be removable");
    }

    #[test]
    fn creates_identifier_slug() {
        assert_eq!(identifier_slug("Example App"), "example-app");
        assert_eq!(identifier_slug("  CEFARI__Desktop!! "), "cefari-desktop");
    }

    fn temp_project_path() -> std::path::PathBuf {
        let suffix = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time should be after epoch")
            .as_nanos();
        std::env::temp_dir().join(format!("cefari-cli-test-{suffix}"))
    }
}
